# SPDX-License-Identifier: PMPL-1.0-or-later
# ClusterFuzzLite configuration for VeriSimDB
# OpenSSF Scorecard Fuzzing compliance

language: rust
main_repo: 'https://github.com/hyperpolymath/verisimdb'
